### ISSUE TITLE
Why extractMetaData turns an object into single element array?

### ISSUE THREAD

**Issue by tomchentw** [yury-dymov/json-api-normalizer#17]
Hi,

I'm new to json-api and this project, and I'm wondering why we turn an object into a single element array in `extractMetaData` function? Specifically, this line:
https://github.com/yury-dymov/json-api-normalizer/blob/master/src/normalize.js#L110

Hence, given a response like this:

```json
{
  "data": {
    "attributes": {
      "title": "123213123"
    },
    "id": "39971d63-debe-4d25-acab-b1b2269dcf09",
    "links": {
      "self": "---"
    },
    "relationships": {
      "authors": {
        "data": [
          {
            "id": "cc46d294-7f4f-4d1d-88a5-8ecc12ffb49c",
            "type": "node--person"
          }
        ],
        "links": {
          "self": "---"
        }
      }
    }
  },
  "included": [
    {
      "attributes": {
        "anchor": null,
        "uuid": "9bbf8dac-fafc-4c5a-8c6b-011e2dce1a9d"
      },
      "id": "9bbf8dac-fafc-4c5a-8c6b-011e2dce1a9d",
      "links": {
        "self": "---"
      },
      "type": "paragraph"
    }
  ],
  "links": {
    "self": "---"
  }
}
```

Where data is an `object`, but it will be turned into a single element array in `meta[endpoint].data`.

Is this expected behaviour?

Thanks

**Comment by yury-dymov** [comment]
Hey @tomchentw, I hope I understood the question but I am not 100% certain. 

The `meta` goal is to help preserve some backend response details, which would be missed otherwise. 

Let's say you call the same endpoint but with different parameters for different screens. After normalization, all the data will be stored and it might be hard or even impossible from application side to fetch only relevant data from the store for the particular screen.

You may read more here https://www.smashingmagazine.com/2017/05/json-api-normalizer-redux/#2-store-collections-as-maps-whenever-possible

**Comment by tomchentw** [comment]
Take the `Endpoint And Metadata` for example:
https://github.com/yury-dymov/json-api-normalizer#endpoint-and-metadata

```js
console.log(normalize(json, { endpoint: '/post-block/2620' }));
/* Output:
{
  question: {
    ...
  },
  postBlock: {
    
  },
  meta: {
    "/post-block/2620": {
      data: [{
        type: "postBlock",
        id: "2620",
        relationships: {
          "question": {
            type: "question",
            id: "295"
          }      
      }]
    }
  }
}
*/
```

If the `json.data` before normalization is an array, then the `meta['/post-block/2620'].data` should be an array. Otherwise, if the `json.data` before normalization is an object, I expect the `meta['/post-block/2620'].data` should be an object as well.

But given the normalize in this line:

https://github.com/yury-dymov/json-api-normalizer/blob/cc8a2233e9e26fd667b3a6fb241eb34a4674104a/src/normalize.js#L108-L110

The result `meta['/post-block/2620'].data` will always be an array, no matter what.

**Comment by tomchentw** [comment]
> @yury-dymov :  It is very likely that you will have many objects of the same type in your store

Yeah, but these objects will be stored in `[type][id]` as a map, and it doesn't affect the `meta` object I'm talking about.

**Comment by yury-dymov** [comment]
What the issue though from the business perspective? 

This is my architectural decision to have the same data structure for all kind requests to make it easier to work with both data and meta for clients. You may have a look at [redux-object](https://github.com/yury-dymov/redux-object), which helps to build JS objects from the normalized store.

**Comment by tomchentw** [comment]
> What the issue though from the business perspective?

It's just making it more consistent with the response from the API. If I request the endpoint `/post-block/2620`, which returns an object, not an array. I'll expect `meta['/post-block/2620'].data` to have a single object pointer to the actual post-block in normalized store.

If I request another endpoint, say `/search-posts?q=whatever`, which returns an array of posts as a result, I'll expect `meta['/search-posts?q=whatever'].data` to have an array as well. This just making it consistent with the API response.

I did look into `redux-object` as well, but it cannot match the needs to build JS object from the `meta` of the normalized store.

**Comment by yury-dymov** [comment]
Well, both of us are repeating the same things again and again, which leads us nowhere. 

I intentionally designed it this way and I still haven't seen any arguments that this approach stops people from doing stuff, which they could otherwise. This design change will be breaking for many people with no good reason.

I encourage you to make a fork and make this design change there. I assume that sometime later it is highly likely that you will find a pattern in your client-side code, which you will extract to fulfill DRY concept and eventually end-up with the same decision I made.

Hence, this is not an issue to me, so I am closing this.

**Comment by tomchentw** [comment]
No worries. I appreciate your response & contribution to this project. Like you said, I just can't figure out why yet (I just met json-api three weeks ago).

**Comment by nratter** [comment]
There's a reason that data is sent back per the JSON API spec as either an object or array. I think it's confusing that single records get stuffed into an array in the metadata in this library. Ultimately, the client-side programmer knows if they are expecting a single record or many. If they know they are expecting a single record, then they have to 'hack' what you have here in the metadata to get the first value of the array. Does this make sense and has anyone's opinion changed here?

**Comment by nratter** [comment]
Please consider reopening this issue
