### ISSUE TITLE
ID missing from normalised resource object

### ISSUE THREAD

**Issue by cwmrowe** [yury-dymov/json-api-normalizer#3]
After normalisation, the resource `id` is successfully used as a `key`, but is lost from the original resource object. 

I see in your examples that you also have the id in the attributes object, but this feels like unnecessary duplication and is not something you find in other JSON API examples.

What do you think about retaining the original ID on the resource object?

**Comment by yury-dymov** [comment]
@cwmrowe after normalization `id` will be a `string` due to JSON nature, so my example shows that we still can preserve original type (almost always `number`) if desired.

Otherwise, I agree with you on unnecessary duplication, so it doesn't make a lot of sense to retain the original ID. Please also check https://github.com/yury-dymov/redux-object/pull/1 on this matter.

Maybe I misunderstand, but I don't see an issue so far. Feel free to provide a practical example or a good reason to change implementation and I might do so :)

**Comment by apsavin** [comment]
@yury-dymov I think you missed the point.

@cwmrowe wrote that you should preserve entity.id during normalization.
He wrote about "unnecessary duplication" about `entity.attributes.id` that you have in all of your examples.

**Comment by apsavin** [comment]
@yury-dymov  would you accept a PR with fix?

**Comment by yury-dymov** [comment]
@apsavin, sure
